/*
 * HelpForm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.gatespace.ui;

/**
 *
 * @author  __USER__
 */
public class HelpForm extends javax.swing.JFrame {

	/** Creates new form HelpForm */
	public HelpForm() {
		initComponents();
		jHelpTextArea
				.setText("This utility will normalize the Broadband Forum's TR-069 Data Model schemas that are defined"
						+ " by a set of XML files located at 'http://broadband-forum.org/cwmp'. These files"
						+ " contain dependencies that are resolved by processing the previous versions of the files as"
						+ " well as common defintion files. This utility normalizes the data model into a single"
						+ " data model definition XML file that can be imported into the Gatespace ESM or used to"
						+ " generate code for the CWMPc client. \n"
						+ "\n"
						+ "Steps:\n"
						+ " 1: Set the Broadband Forum Data Model directory to the directory containing the "
						+ " data model definition files downloaded from the URL above.\n"
						+ "\n"
						+ " 2: If generating a device data model set the CWMPc working directory in the device panel."
						+ " This is the destination directory that the normailized"
						+ " definition file and the various generated code files is written."
						+ " Then select the device data model from the list.\n"
						+ "    If generating a service data model set the CWMPc working directory for the service"
						+ " in the services panel and then select the service data model for the list.\n"
						+ "\n"
						+ " 3: Cick the 'Normalize' button to create the normalized data model definition."
						+ "\n"
						+ " 4: Click the 'Profile Filter' button and select the required profiles for the data model."
						+ "\n"
						+ " 5: If specific Object or parameters are to be included or excluded click the 'Object/Param'"
						+ " button and select or deselect the objects and parameters."
						+ "\n"
						+ " 6: Click the 'Generate Code' button to generate the tables and getter/setter stubs code.\n"
						+ "\n"
						+ "The following files are created:\n"
						+ "dm-instance.xml - The normalized data model definitionf file before profile filtering.\n"
						+ "code-gen-dm-instance.xml - The normalized data model definition following profile and"
						+ " object/parameter filtering.\n"
						+ "dm-selected-pofiles.xml - The xml definition of the selected profiles.\n"
						+ "xx.c - The getter/setter stubs file where xx is the 2nd-level object name.\n"
						+ "xx.h - The header file containing the typedef struct definition for the parameters contained"
						+ " in each object.\n"
						+ "tables.c - The C object and parameter definitions for the data model.\n"

				);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jDialog1 = new javax.swing.JDialog();
		jScrollPane1 = new javax.swing.JScrollPane();
		jHelpTextArea = new javax.swing.JTextArea();

		javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(
				jDialog1.getContentPane());
		jDialog1.getContentPane().setLayout(jDialog1Layout);
		jDialog1Layout.setHorizontalGroup(jDialog1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		jDialog1Layout.setVerticalGroup(jDialog1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jHelpTextArea.setColumns(20);
		jHelpTextArea.setLineWrap(true);
		jHelpTextArea.setRows(5);
		jHelpTextArea.setWrapStyleWord(true);
		jScrollPane1.setViewportView(jHelpTextArea);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 485,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 592,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HelpForm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JDialog jDialog1;
	private javax.swing.JTextArea jHelpTextArea;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}