/*
 * OptionsDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.gatespace.ui;

/**
 *
 * @author  __USER__
 */
public class OptionsDialog extends javax.swing.JDialog {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1002658203643934124L;
	private GlobalOptions gOpt;

	/** Creates new form OptionsDialog */
	public OptionsDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		gOpt = StartUp.gOpt;
		jCheckBoxGenTypedef.setSelected(gOpt.genObjTypeDefs);
		jCheckBoxGenAlias.setSelected(gOpt.genAliasGetSet);
		jCheckBoxIgnoreDeprecated.setSelected(gOpt.ignoreDeprecated);
		jCheckBoxIgnoreDeprecatedAliasParam
				.setSelected(gOpt.ignoreDeprecatedAlias);
		jCheckBoxGenSingleFile.setSelected(!gOpt.seperateStubs);
		jCheckBoxAddPreambleFiles.setSelected(gOpt.addPreambleFiles);
		jCheckBoxMergeOldImp.setSelected(gOpt.mergeImplementationCode);
		jCheckBoxMergeCTemplates.setSelected(gOpt.mergeImplementationCode);
		jCheckBoxGenAddObjStatics
				.setSelected(gOpt.genAddObjStaticInstanceStubs);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jCheckBoxGenTypedef = new javax.swing.JCheckBox();
		jCheckBoxGenAlias = new javax.swing.JCheckBox();
		jCheckBoxIgnoreDeprecated = new javax.swing.JCheckBox();
		jCheckBoxGenSingleFile = new javax.swing.JCheckBox();
		jCheckBoxAddPreambleFiles = new javax.swing.JCheckBox();
		jButton1 = new javax.swing.JButton();
		jCheckBoxMergeCTemplates = new javax.swing.JCheckBox();
		jCheckBoxMergeOldImp = new javax.swing.JCheckBox();
		jCheckBoxGenAddObjStatics = new javax.swing.JCheckBox();
		jCheckBoxIgnoreDeprecatedAliasParam = new javax.swing.JCheckBox();

		jCheckBoxGenTypedef
				.setLabel("Generate object typedef and parameter access code.");

		jCheckBoxGenAlias
				.setText("Generate Alias Get/Set in CWMP framework (Amend. 4)");
		jCheckBoxGenAlias
				.setActionCommand("Generate Alias instance set and get label code(CWMP v1.3).");
		jCheckBoxGenAlias
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jCheckBoxGenAliasActionPerformed(evt);
					}
				});

		jCheckBoxIgnoreDeprecated.setText("Ignore all DEPRECATED parameters.");

		jCheckBoxGenSingleFile
				.setLabel("Generate a single stubs file for all objects.");

		jCheckBoxAddPreambleFiles
				.setLabel("Add peamble files to stubs and header files.");

		jButton1.setLabel("OK");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jOKButtonActionPerformed(evt);
			}
		});

		jCheckBoxMergeCTemplates
				.setLabel("Merge *.c files from templates directory.");

		jCheckBoxMergeOldImp
				.setLabel("Merge *.c files from previous implementation.");

		jCheckBoxGenAddObjStatics
				.setLabel("Generate AddObject stubs for static Instance (eStaticInstance) objects.");
		jCheckBoxGenAddObjStatics
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jCheckBoxGenAddObjStaticsActionPerformed(evt);
					}
				});

		jCheckBoxIgnoreDeprecatedAliasParam
				.setText("Ignore DEPRECATED 'Alias' parameters.");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jCheckBoxIgnoreDeprecatedAliasParam)
												.addComponent(
														jCheckBoxGenAlias,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														488,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jCheckBoxIgnoreDeprecated,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														488,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jCheckBoxGenSingleFile,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														488,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jCheckBoxAddPreambleFiles,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														488,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jCheckBoxMergeOldImp,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														488,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jCheckBoxMergeCTemplates,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														488,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														93,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(21, 21,
																		21)
																.addComponent(
																		jCheckBoxGenAddObjStatics,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		488,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(
														jCheckBoxGenTypedef,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														488,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(20, 20, 20)
								.addComponent(jCheckBoxGenTypedef,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(4, 4, 4)
								.addComponent(jCheckBoxGenAddObjStatics,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jCheckBoxGenAlias,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(
										jCheckBoxIgnoreDeprecatedAliasParam)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										6, Short.MAX_VALUE)
								.addComponent(jCheckBoxIgnoreDeprecated,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jCheckBoxGenSingleFile,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jCheckBoxAddPreambleFiles,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jCheckBoxMergeOldImp,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jCheckBoxMergeCTemplates,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jButton1)
								.addGap(33, 33, 33)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jCheckBoxGenAddObjStaticsActionPerformed(
			java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBoxGenAliasActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jOKButtonActionPerformed(java.awt.event.ActionEvent evt) {
		setVisible(false);
		gOpt.genObjTypeDefs = jCheckBoxGenTypedef.isSelected();
		gOpt.genAliasGetSet = jCheckBoxGenAlias.isSelected();
		gOpt.ignoreDeprecated = jCheckBoxIgnoreDeprecated.isSelected();
		gOpt.ignoreDeprecatedAlias = jCheckBoxIgnoreDeprecatedAliasParam
				.isSelected();
		gOpt.seperateStubs = !jCheckBoxGenSingleFile.isSelected();
		gOpt.addPreambleFiles = jCheckBoxAddPreambleFiles.isSelected();
		gOpt.mergeImplementationCode = jCheckBoxMergeOldImp.isSelected();
		gOpt.mergeTemplateCode = jCheckBoxMergeCTemplates.isSelected();
		gOpt.genAddObjStaticInstanceStubs = jCheckBoxGenAddObjStatics
				.isSelected();
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				OptionsDialog dialog = new OptionsDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JCheckBox jCheckBoxAddPreambleFiles;
	private javax.swing.JCheckBox jCheckBoxGenAddObjStatics;
	private javax.swing.JCheckBox jCheckBoxGenAlias;
	private javax.swing.JCheckBox jCheckBoxGenSingleFile;
	private javax.swing.JCheckBox jCheckBoxGenTypedef;
	private javax.swing.JCheckBox jCheckBoxIgnoreDeprecated;
	private javax.swing.JCheckBox jCheckBoxIgnoreDeprecatedAliasParam;
	private javax.swing.JCheckBox jCheckBoxMergeCTemplates;
	private javax.swing.JCheckBox jCheckBoxMergeOldImp;
	// End of variables declaration//GEN-END:variables

}